
* 2015 02 05 立春风大月圆
风满天 月更圆 夜凉如水春意寒 
人已静 夜正阑 独饮无言酒难酣 
愁入酒 更难眠 知与谁同共婵娟

* 2014 12 07 配图小孩手持菜刀
面朝黄土背朝天 右手菜刀左手拳 一脸横肉路中站 是人是佛皆敢拦

* 2014 12 20
对老子来说，无为是工具。对庄子来说，无为是目的。

* 2015 02 06 
月下河水边
树影蹒跚
相依相偎风不寒
低语倾诉春水静
情意绵绵

* 2015 02 17 年前上坟
岁月荒了山
新坟又添
树欲静而风更寒
枯枝败叶覆新雪
更似旧年

* 2015 02 18
孤独逃避庸俗
冷漠保护脆弱
幽默掩盖造作
文艺充当情色

* 2015 03 05 正月十五
要把想你的心情收敛
我把门窗关严
但五彩的烟花
却把天空照映成你的笑脸

要把想你的心情收敛
我独自走在河边
但倒映在水面的灯火
却让河水起了波澜

要把想你的心情收敛
我把酒杯斟满
但朦胧的醉意中
却听见你一次次温柔的呼唤

要把想你的心情收敛
我用手去拢住一缕青烟
但它化为更淡更多
却向心中蔓延

要把想你的心情收敛
我吃了两个老北京鸡肉卷
但鸡肉卷吃起来
却远不如烩面片儿Q弹

要把想你的心情收敛
我又煮了一锅汤圆
但雪白的汤圆
却让我对白面馒头更加怀念


* 2015 03 04
没人挂念你离开，也没人期待你回来。痛苦无人分担，快乐没人共享。想积极一点觉得没什么意义，想堕落一下，又没有勇气。


* 2015 03 09 
剥开一层又一层，剥得手指头火辣辣地疼，吃到嘴里甜丝丝，让你眼泪流成行。

* 2015 03 16
星光就可以用来取暖
圆月已足够点燃热情
一个眼神就可以丰富贫瘠的幻想
一个微笑已足够占据荒芜的心灵
但春天的夜晚沁凉如冰

* 2015 04 01 雨 
春夜醉卧梦中醒 不怨风声 不怨雨声 无言枯坐数空瓶 愁绪一瓶 寂寞一瓶
推门举伞雨中行 一盏街灯 两盏街灯 一朵玉兰落泥泞 是风无情 是雨无情？

* 2015 04 04
三观并不是决定一个人的根本因素。审美偏好或者说品味才是。

* 2015 04 16 奥森公园
绿头鸭 碧桃花 小桥流水一池蛙
春水皱 立白鹭 海棠渐落春不驻
花堪折 酒当喝 良辰美景竟虚过  


* 2015 04 16
         旅游是
无趣朋友间最好的谈资 
空白人生中廉价经验值 
乏味生活上显著的存在感 
无知头脑里最直接的见识

* 2015 04 28
        旅游不是
屌丝望尘莫及的高级消费
宅男感受不到的浪漫体会
卢瑟难以企及的身价资本
土鳖无法理解的人生意义

* 2015 04 29 雨后暮春 蝶恋花
梨花落尽翠色深 风拂小径 落英乱纷纷 疏星几点入杯饮 薄云遮月淡树痕
海棠凋谢春又暮 雨润帘门 杨花不入户 杜鹃不知独眠苦 伴啼明月照愁处 


* 2015 05 10
如果男人需要作一把保护伞，那女人应该是温柔乡。如果男人需要给人安全感，那女人应该懂得体谅。男人需要有征服的勇气，那女人应该善解人意。

* 2015 05 10
最不贴切的情况莫过于男的懦弱，女的刻薄。男的愚蠢，女的幽默。

* 2015 05 21
检以养德，实际上不是在作道德训练，而是在培养一种品位

* 2015 05 21
人就应该在不被忧愁伤害的前提下适当地忧伤，因为生活本来就是如此。无缘无故地说自己很高兴，那不过是脱离现实的自欺欺人。

* 2015 05 22
这就是我的周末
有心出去溜达，看着满街的大白腿上火
无奈在屋宅着，越琢磨越觉得自己撸瑟
想要找人聊天，三两句话就会变得沉默
自己一人喝酒，又会觉得这是一种堕落
打开电脑干活，都已经累得再坐不住了
躺在床上看书，盯了半天不知说的什么
去商场看电影，四周全都是情侣腻歪着
我就这样麻木，不知活着的意义是什么


*  2015 05 23
色心要多一些，否则不知欣赏美丽，太可惜。色胆要少一些，否则很容易变得不正经，损人品
纵情不纵色


* 2015 05 29
凡出异常 必有妖孽


* 2015 06 17 长相思 上下班
八号线 六号线 常跟美女贴身站 沾一身香汗 
早七点 晚八点 没有时间去锻炼 腹肌要不见 


* 2015 06 21 长相思 矫情和感情
这也不行 那也不行 装模作样假惺惺 这就是矫情
对人真诚 对己真诚 理解包容又热情 这才叫感情


* 2015 06 30 长相思 雨过天晴
 一场雨 一场风 二零一五过半程 人生恍如梦
天色青 已放晴 清凉夏雨洗星辰 明月寂无声


* 沒有人願意看到現實的全部。大多數的人只希望看到他們想看的部分 z


* 2015 07 13
成熟就是不再为无法掌控的事情忧心忡忡
成熟就是对多数人的理解和认同不再热衷
成熟就是给别人更多的理解和更多的认同
成熟就是坚持信仰再也不为纷繁杂乱所动

成熟是世界很大，却去内心寻求发现
成熟是心中热情似火，脸上却很平淡
成熟是望着她渐渐远离，却不再呼唤
成熟是按时睡觉按时起床，按时上班


* 2015 07 15
又是一个下雨的夜晚
雷声轻轻滚落在窗前
曾经
春天寂寞的风
轻抚得玉兰凋谢
现在
夏天烦恼的雨
冲淡槐花的清甜
但是
热烈的蔷薇会探出花丛
故意的矜持藏不住笑靥
虽然
这又是一个下雨的夜晚


* 2015 07 19
离开了不被人想起，不回来也不被人惦记，痛苦无人分担，快乐没人一起嗨皮，
想积极一点觉得没什么意义，
要堕落一下又没有勇气。 


* 2015 07 23
又是一个下雨的夜晚
一朵黄色的月季探出了围栏
秃尾巴的小麻雀又在满地的槐花中翻检
暴雨突袭的地铁站
没人注意到我在翘首期盼
不是希望雨停
而是希望一个人出现
她举着伞拾起裙䙓站在雨中
就像一朵淡雅的玉兰
从平静，到焦急，最后闷烦
她脸上的微笑穿过了雨帘
就在看到我的那一瞬间
“杀千刀的！嘎哈让我等你这么长时间？”
“好好好，今天我来洗碗”
“洗碗？你今天休想吃饭！”
然而
yy并没有什么卵用
你必须勇敢地走入雨中
别忘了挽起裤管……


* 2015 07 27
又是一个下雨的夜晚
黑夜深沉兮阴雨绵绵
雷声渐远兮灯火阑珊
杯中无酒兮乌云不散
胸中有话兮口中难言
雀鸟归巢兮相语成欢
微风虽凉兮孤枕难眠


* 2015 07 31
肤白胸大红红的嘴 细腰翘臀大长腿 眉望远山鬓乌黑 一双眼睛含秋水


* 2015 06 26
每当在大街上看到美女。。。 
就会有一只蛤蟆在我心里乱撞-->然后心中会油然而生一丝惆怅-->再接下来又迸发出强烈的渴望-->对自己说：当街看大白腿，不如退而结网-->最后呢，却仍旧回到原来一个人的老路上。 


* 2015 08 01
煎饼侠，你为何还不出现？我已经喊了你整整十七八遍！ 
虽然满场的人们都笑翻了天，可是我却忍受着右边那哥们儿的阵阵汗酸。要说汗酸味也并非是无法忍受，但美女就坐在我的左边！万一她误会了那汗味儿来自于我，我岂不是白白浪费了洗澡的时间？早知如此，那香喷喷的舒肤佳，我应该多蹭几遍，或许可以抵消这浓烈的汗酸。 
煎饼侠，你赶快给我出现！去消灭这个龌龊的哥们儿，用葱花儿和鸡蛋。 
  
煎饼侠，你为何还不出现？我已经喊了你整整十七八遍！ 
每当镜头扫过柳岩，我身后的小孩，就踹得我前仰后翻，高兴地是连蹦带颠。要知道，那珍贵的特写转瞬即逝，那诱人的胸脯不会再给看第二遍！虽然是美女请客买的票。但我也想看回票钱。你这小盆友，不能凭借年龄的优势就来随意打扰我这个猥琐男。逼急了，我跟可耐的小女孩儿也能翻脸！ 
煎饼侠，你赶快给我出现！去消灭这个邪恶小孩儿，用葱花儿和鸡蛋。 
  
煎饼侠，你为何还不出现？我已经喊了你整整十七八遍！ 
为什么美女肯花钱请看电影，却让我一个人吃饭？在这个下雨的夜晚，或许没准可能大概说不定会有一些浪漫。怎奈这满腹的疑团，让我连接吻一般口感的烩面片儿也难以下咽。 
煎饼侠，你赶快给我出现！给我来一个煎饼，多加葱花儿，要俩鸡蛋。


* 2015 05 30
今天走了2万步，12公里 
下午开始的时候稍微有点热，不过有风，还挺好的。奥森里头白腿翘臀小细腰儿依旧很多。一边走一边欣赏，一点都不觉得累。 
回来的时候正当我大口吞嚼卤肉三明治的时候，邻桌的一个五六岁的小姑娘一边啃着包子一边用她那水灵灵的大眼睛直勾勾地瞅我。瞅得我心里直发毛。我转过脸拿餐巾纸几次三番地擦了嘴确认嘴巴子上没有食物残渣之后，转回脸来自信地直接跟她对视，并且潇傻地笑了一下。这时，她反而不好意思了，拿着包子绕到椅子后面去玩，并且透过椅背的缝隙再次偷偷地看我。 
正当我准备把这一大口食物嚼好了咽下去作个鬼脸的时候，她对面的妈妈发现了我们俩的目光交流。转头看了我一眼。这下完蛋了，一双天真的大眼睛我尚可以对付，再加上他妈的一道风情万种的眼神，我双拳难敌四手，顿时甘拜下风。赶忙灰溜溜地低下头使劲儿往嘴里塞东西,吃完回来继续灌水。
  

* 2015 02 23
我琢磨出来的恋人之间的三种境界 
第一，相依相伴。最基本的。不管快乐还是悲伤，都有ta在身边。遇到痛苦会减半，遇到 
快乐会加倍。让你觉得不再孤单。 
  
第二，心心相印。更高一级。你知道这个世界上有人理解你支持你。ta甚至可以远在天 
边。你可以为此忍受别人无法忍受的痛苦，感受别人无法体会的快乐。 
  
第三，两情相悦。最高追求。你会因为另一个人的存在而感到发自内心的愉悦。心无旁 
骛，忘记周围的痛苦，不在乎其他事情带来的快乐。粗茶淡饭不觉其差，山珍海味不觉其 
美。每天都在一种忘我的催眠状态之中。
  

* 2015 08 07
扭曲就是幻想和现实之间的差距


* 2015 08 08
昨天我正站在路边-- 
看着一辆一辆的汽车，准备过马路。突然一只小老鼠从路边跑了过来，径直跑到我的两脚之间，停了下来。大概是因为它在空旷的路上找不到个掩护很没有安全感的缘故。误以为我不是一个活物，所以前来栖身。
我低头对它说：我去。你胆儿够肥的，竟然没把我放在眼里！
它抬起头来诧异地望了我一眼，撒腿就跑。
其实在这空旷的路上，我也挺没有安全感的。刚想喊它停下来，撘个伙，聊聊天啥的。怎奈它速度很快，转眼已经消失在人海中了。


* 2015 08 11
程序员的业余项目开始于寂寞，失败于孤单。


* 2015 09 14
合格的程序员让程序适应环境，不合格的程序员为程序创作环境


* 2015 09 29
一个桃核小筐被弄断了
晚上不睡觉 早上不起床 嘎嘣一声响 毁了一个筐 挂了十多年 不再成一双


* 2015 10 4
最幸福的时候就是: 一个女人主动把那只柔软的小手儿伸过来拉你手的时候。这时，你会感到这个冷漠的世界上还有那么一个人是愿意跟你建立联系的，还有那么一个人是想依赖你的，还有那么一个人是想亲近你的，还有那么一个人是喜欢你的，还有那么一个人是愿意跟你在一起的。


* 2015 10 22
又是一个下雨的夜晚
夜色中
是秋雨绵绵
街道上
是黄叶片片
灯光里
人们很温暖
凉风中
用秋裤御寒
载着你
是梦想的船
挡着雨
是破旧的伞
相见时
你语笑言欢
分别了
我独自流连


* 2015 10 24
大龄男女的价值在于岁月沉淀了什么？
岁月沉淀下来的只剩下苍老的容颜，虚弱的身体，萎靡的精神，和心灵的扭曲。唯独没有的就是美好的回忆。


* 2015 11 01 2015 10 31 在雕刻时光咖啡馆 第一次去咖啡馆
窗外秋天的阳光灿烂
窗内晒得让我额头冒汗
一看台灯
充满了文艺范
显摆着拿出我的iPhone6拍一个照片
抬头一看
苹果笔记本就有一大片
美女在低头听歌看书
帅哥在讨论商业方案
一个安静的港湾
我只好小声问：服务员，有没有回锅肉盖饭？
窗外的秋天阳光灿烂
你的依偎
让我紧张得手心出汗
苹果笔记本儿发光的logo
更是变成了一只只偷窥的眼
盯得我不由自主摆弄起了杯盘
窗外的秋天阳光灿烂
你玩你的手机
我扯我的淡
也不知道你听没听见
就这样一直到日斜西山


* 2015 11 12
最悲剧的事情莫过于无知的人有自信，愚昧的人有热情


* 2015 11 14
半夜三更
拍了这张邪恶的照片
感觉很适合这个雾霾笼罩的夜晚
这么污浊的空气
不知有多少人咳嗽
多少人哮喘
也不知有多少人痛苦地呼吸
多少人得了肺炎
宇宙的中心五道口
照样熙熙攘攘灯火阑珊
戴口罩的
你有什么可以防范？
健身房里的
又有什么意义去锻炼？
街上的行人都不见笑脸
是一具具僵尸游荡在道路两边
[衰][骷髅]👿👻😱


* 2015 11 22
好不容易下雪天 屋里闷着在上班 中午食堂没有饭 看雪景在朋友圈


* 2015 12 13
愚蠢是一种道德上的缺陷 z
情商低是愚蠢的表现


* 2015 12 26
看了电影《乱》（行太多，怕影响阅读，没有加回车。。。）
不要说我是文艺青年，我看电影从来都是打发时间。我从来都不记得导演，也很少认识哪个演员。相对于文艺青年中有口皆碑的，我更喜欢看或火爆，或搞笑，或探险，或科幻的好莱坞无脑大片。
黑泽明，我也是听说过的。看过《罗生门》，那也只是在大约一年以前。因为被牛人提及，就是《少年派奇幻旅行》的导演李安。后来有一次晚上走进一家咖啡馆。人少，安静，真是难得一见。等寻了一个角落坐下之后，发现身后的屏幕上放着一部黑白片。无聊之际，扭过身去看了几眼。这时，老板手里擦着杯子竟然跟我搭讪：你也喜欢黑泽明的影片？“我。。。我看电影并没特殊偏好，只随便看。。。”  “糗大了”那个QQ表情突然在心中浮现。心说：这次一定会被看扁。可是那个老板竟然无动于衷，既没对我嗤之以鼻，也没对我另眼相看。大概因为三更半夜的人少无聊，只拿我当个听众打发时间。“黑泽明是大师，他的电影都不一般。这个电影的名字叫'椿三十郎'，你知道为什么叫这个名字吗？。。。”还没等我找到理由搪塞住不知道的尴尬。“其实就是主人公随口看见一棵树给自己起的名，有一种幽默的成分在里面。。。”。我刚要应和一声“哦” 。老板连眼皮都没抬就已经开始跟另一个客人攀谈。我这手心已经攥了一把汗，暗下决心，一定要把这个电影仔细看一遍！
就这样，我回去之后，搜到了这个电影（请原谅我看的是盗版），顺便还搜到了黑泽明的其他影片，其中就包括《乱》。
乱？呼啦啦的记忆突然在我眼前浮现！那时候还上中学，每周末晚上电视里都放国外的影片。我曾记得看过一个日本电影，故事悲剧，场面宏大，色彩斑澜。在我幼小的心灵里留下了深刻的印象，就这么神奇地记忆了许多年！也许并非我的记忆力很好，只不过它的名字太短。但是大师的手段果然高明，既能让懂行的人看得头头是道，又能打动一个无知少年。
那时候我喜欢学习，当然更喜欢玩。似乎也并不是每天都很快乐，也有很多愁绪绕在心间。至于为何发愁，现在已经想不起个所以然。有时会受到小混混的欺负，我也会回敬他们几拳。兜里并没有零花钱，但是有很多小伙伴，我们下雨时打球，下雪时撒欢。
那时，总有一个女生，每当她一出现，男生们就竭力表现。她高挑白净 ，一头黑发梳成长长的马尾辫，她是老师眼中的三好学生，她是同学心里的榜样模范。她是让成绩好的男生想接近又嫉妒的对手，她是成绩差的男生无法攀登的高山。每周换座儿，周围的人都找各种理由要挨在她这一边。每次考试结束，都有人找她讲解试卷。不知道有多少人自以为得到了她的青睐，也不知道有多少人在心中对着她名字暗暗默念。
也不知道谁tmd触发了楼下汽车的警报，吱哇乱叫了半天，直接把我的思路打断。瞬间又回到了雾霾笼罩的2015年。这就是我没头没尾的年底总结，希望有一个顺利的2016年。


* 2016 01 02
完美主义热衷选择
现实主义别无选择
理想主义忠于选择


* 2016 01 02
努力作一个完美主义者
不要热衷于选择
世界充满了缺陷
时间却并没有很多
努力作一个现实主义者
要正视自己的选择
妥协是幸福的智慧
事实就不会那么冷漠
努力作一个理想主义者
去忠于自己的选择
就算周遭满是嘲讽
也依然真心热爱生活


* 2016 01 03
坐在马桶上突然想起来《老炮儿》
甭管是爱情，友情。还是事业，江湖。甭管你是杀人放火还是救国救民，也甭管你是地痞流氓还是仁人志士。作为一个爷们儿，最重要的是有一个自己为之信仰的原则。为此赴汤蹈火在所不辞，明知失败却面不改色。这才是一个爷们儿受人佩服的核心。用老炮儿的话说：讲究。
人们喜欢老炮儿这个电影，不是喜欢老炮儿的寒酸，也不是喜欢老炮儿的落伍，更不是喜欢老炮儿的架子。而是佩服他作人肯坚持自己的原则。
这种原则，往轻了说，那是一个人的信仰，往重了说，那是一种道德。在一个道德滑坡沦丧的社会中，人们越来越觉得这种由内而外讲规矩，自发自觉守道德的人太少了。这样的人已经像老炮儿一样被社会抛弃了。人们既对这样的人向往，却又不敢效仿。只能眼睁睁的看着这种规矩这种原则随着老炮儿这样的人一起被淘汰。最后，这个社会因为人们都不遵守规矩而进入负反馈循环，大家一起受到伤害。
md，在马桶上坐得我腿麻得都站不起来了。。。


* 2016 01 17 腊八 下雪
身后的脚印 
是过去波澜不惊
前方的洁白 
同未来一样宁静
脚下的松软
正在与温油同行

这温油融化冰雪
这松软如沐春风
像奶茶暖人心脾
似明灯指引路程

孤独的蝙蝠侠
被一个声音轻轻呼唤
忧愁的小丑
有一种渴望在内心升腾
那是因为
腊八粥不再冰冷

老板
一碗腊八粥多放糖
内什么微信支付宝刷哪个有优惠？


* 2016 02 01
批评别人，是懂规则。理解别人，才是有道德


* 2016 02 08
你们一共收发红包多少个？
我收到两个，只拆了一个，发送了三个，其中两个出于被迫。要问总金额？ 连二十块都没超过！除夕晚上鞭炮齐鸣，我拿着手机灌水席地而坐。大年初一串门拜年，我自己听了一下午的歌。脸也没洗，头发像鸟窝。牙也没刷，衣服也没换过。2016猴年开始就是这么过的！无聊仅次于ccav的春晚，乏味胜过给春晚洗地地新闻联播。


* 2016 02 10
各位青年，你们说啥是文艺？
有人说文艺是感受美的能力
有人说文艺是可以表达情绪
文艺是美女挡住脸贴张照片
文艺是唱歌故意跑调的逗比
文艺是涂指甲油的一双素手
文艺是大白长腿上戴着护膝
文艺是吃货煲汤烤鸭后拍菜
文艺是偶尔消失突然晒猫咪
文艺是骚聊歪歪加唉声叹气
文艺是秀各种风景旅游各地
我觉着文艺不过是一种游戏
玩得多弄出花样就成了文艺
那么你属于三类之中哪一类？
我觉着自己属于第三类二逼


* 2016 03 18
这大雾霾的春天

仿佛听到了鸟的言语
楼下的清洁车在收垃圾
貌似闻到了花的香气
品一下其中有汽车尾气
似乎感到了春的气息
夹杂着一些雾霾的油腻
已经迫切脱下了棉裤
还有一丝丝凉意
早已举起手机准备自拍
花没开叶也没绿
大腿已经洗得白白净净
还需穿牛仔T恤
需要一些新鲜的刺激
让郁闷不再持续


* 2016 03 27
有的人追求刺激
有的人追求权力
有的人追求财富
有的人追求嗨皮
其实
活得淡定
想得明白
看得清晰 
这样也就可以


* 2016 04 12
可来了一个下雨天（回车换行随意插入字里行间）
杨絮加土这盘儿沙拉
吃腻了整个春天
喝到印堂发黑的白云
终于出现在天边
感了冒着了凉的春风
让太阳打了冷战
起床之后
是否配备齐了雨衣雨伞？
出门之前
是否准备好了磕磕绊绊？
门里
有意马心猿
门外
是细雨绵绵
海棠花着了雨
会更加娇艳
杨柳树被打湿
将绿更大片
这春天的第一场雨
睡起觉来可以心安

* 2016 04 16 门
技术中心领导因为关门声音太大，特意发邮件指责众人，还特意早上上班时间去蹲点。。。

很久很久以前
有一扇门
它安全可靠开关方便
它忠于职守老实本分

但是----
人们进出的时候
它却发出很大的声音
这个声音让人心烦意乱
这个声音听起来不开心
这个声音充满怨恨
这个声音饱含不平
这个声音打断人的思路
这个声音让人胆战心惊

终于----
有一个人忍无可忍
他采取行动
他付出成本
他捶胸顿足守候在门前思考
他仰望苍天站立在门后发问
为什么？？
为什么人们这么不小心认真！！
他对人们提出了批评
甚至上升到道德水准
这是对世界的不满
这是对苍生的拷问

然而----
门依然发出很大的声音

那个人----
从愤怒到疑惑再到灰心
失望地对着门痛哭涕零
当他哭得精疲力竭
当他哭得昏昏沉沉
突然那扇门开口说话
语气沙哑又老态龙钟

门说----
感谢你注意到我的呐喊
我终于得到了人的关心
我不想被摔
那样我很疼
但解决问题的姿势有很多种
为何你要改变最难改变的人？
你的目的
是没有声音安心睡觉
人的目的
是进进出出奔赴前程
其实
我的门禁太紧
还有
我的阻尼太松
麻烦你帮我修理一下
我保证每天安安静静

那个人----
在昏昏沉沉中醒来
因为打了一个激灵
一个声音还在耳边回荡
语气沙哑而又老态龙钟

----
这才是以门为本
这才是符合人性
这是爱的源泉
这是道德范本
这才是解决问题的正确姿势
这才是设计规则的依据根本
......
